subworkflow main_workflow:
        workdir: ".."
        snakefile: "../Snakefile"

rule index_cDNA_file_human:
	input: "data/Homo_sapiens.GRCh38.cdna.all.fa"
	output: "results/kallisto/GRCh38.idx"
	conda: "envs/kallisto.yaml"	
	shell: "kallisto index -i {output} {input}"

rule index_cDNA_file_mouse:
	input: "data/Mus_musculus.GRCm38.cdna.all.fa"
	output: "results/kallisto/GRCm38.idx"
	conda: "envs/kallisto.yaml"
	shell: "kallisto index -i {output} {input}"


def get_index_file (wildcards):
	if wildcards.accession in config['mouse_accessions']:
		return ('results/GRCm38.idx')
	else:
		return ('results/GRCh38.idx')

def get_input_files (wildcards):
        if wildcards.accession in config['all_paired_end']:
                input_files = [
			       'results/trimmed_fastq/{}_1_val_1.fq.gz'.format(wildcards.accession),
                               'results/trimmed_fastq/{}_2_val_2.fq.gz'.format(wildcards.accession)
                              ]
                return(input_files)
        else:
                input_file = [
                              "results/trimmed_fastq/{}_trimmed.fq.gz".format(wildcards.accession)
                             ]
                return(input_file)

rule kallisto_quant:
        output: "results/kallisto/{accession}/abundance.tsv"
        input: 
                index=get_index_file,
                fastq=get_input_files
        conda: "envs/kallisto.yaml"
        log:   "logs/{accession}_kallisto.out"
        params:
               frag_length_mean=180,
               frag_length_sd=20
        script: "kallisto_quant.py"


