#!/bin/bash

rule create_gene_table:
        output:
           "results/gene_table_created.txt"
        script:
           "create_gene_table.py"

rule create_gene_species_table:
        output:
           "results/gene_species_table_created.txt"
        script:
           "create_gene_species_table.py"

rule create_utr_lengths_table:
	output: "results/utr_length_table_created.txt"
	script: "create_utr_length_table.py"

rule create_mRNA_table:
        input:
           "exe/SQL/SQLite/create_mRNA_table.py"
        output:
           "results/mRNA_table_created.txt"
        shell:
          "{input} {output}"

rule create_Tissues_table:
        input:
           "exe/SQL/SQLite/create_tissues_table.py"
        output:
           "results/tissues_table_created.txt"
        shell:
           "{input} {output}"

rule create_samples_table:
        input:
          dependency_tissue="results/Tissues_table_loaded_hsa.txt"
        output:
           "results/samples_table_created.txt"
        script:
           "create_samples_table.py"

rule create_runs_table:
	output: "results/runs_table_created.txt"
	script: "create_runs_table.py"

rule create_expression_profiles_table:
         input:
            script="exe/SQL/SQLite/create_expression_profiles_table.py",
            dependency="results/mRNA_table_created.txt"
         output:
            "results/expression_profiles_table_created.txt"
         shell:
            "{input.script} {output}"

rule create_species_table:
        input:
           "exe/SQL/SQLite/create_species_table.sql"
        output:
           "results/species_table_created.txt"
        shell:
           "sqlite3 filtar.db < {input} && touch {output}"

rule create_mirna_table:
        input:
           script="exe/SQL/SQLite/create_mirna_table.py",
           dependency="results/species_table_created.txt"
        output:
           "results/mirna_table_created.txt"
        shell:
           "{input.script} {output}"
