#!/bin/bash

rule create_gene_table:
        input:
           "src/create_gene_table.sql"
        output:
           "results/gene_table_created.txt"
        shell:
           "mysql -u tgac --password=tgac_bioinf -h tgac-db1.hpccluster bradleyt_filtar < {input} && touch {output}"

rule create_gene_species_table:
        input:
           "results/tx_and_gene_IDs.txt",
           sql="src/create_gene_species_table.sql"
        output:
           "results/gene_species_table_created.txt"
        shell:
           "mysql -u tgac --password=tgac_bioinf -h tgac-db1.hpccluster bradleyt_filtar < {input.sql} && touch {output}"

rule create_mRNA_table:
        input:
           "exe/SQL/SQLite/create_mRNA_table.py"
        output:
           "results/mRNA_table_created.txt"
        shell:
          "{input} {output}"

rule create_Tissues_table:
        input:
           "src/create_Tissues_table.sql"
        output:
           "results/tissues_table_created.txt"
        shell:
           "mysql -u tgac --password=tgac_bioinf -h tgac-db1.hpccluster bradleyt_filtar < {input} && touch {output}"

rule create_experiments_table:
        input:
           "src/create_experiments_table.sql"
        output:
           "results/experiments_table_created.txt"
        shell:
           "mysql -u tgac --password=tgac_bioinf -h tgac-db1.hpccluster bradleyt_filtar < {input} && touch {output}"

rule create_expression_profiles_table:
         input:
            "src/create_expression_profiles_table.sql"
         output:
            "results/expression_profiles_table_created.txt"
         shell:
            "mysql -u tgac --password=tgac_bioinf -h tgac-db1.hpccluster bradleyt_filtar < {input} && touch {output}"

rule create_species_table:
        input:
           "exe/SQL/SQLite/create_species_table.sql"
        output:
           "results/species_table_created.txt"
        shell:
           "sqlite3 filtar.db < {input} && touch {output}"

rule create_mirna_table:
        input:
           script="exe/SQL/SQLite/create_mirna_table.py",
           dependency="results/species_table_created.txt"
        output:
            "results/mirna_table_created.txt"
        shell:
            "{input.script} {output}"
