rule salmon_index:
        input:
            "data/{species_prefix}.cdna.all.fa"
        output:
            "results/salmon/{species_prefix}"
        threads: 8
        shell:
            "salmon index --threads {threads} -t {input} -i {output} --type quasi -k 31"

def get_input_files (wildcards):
        if wildcards.accession in config['all_paired_end']:
                input_files = ['results/trimmed_fastq/{}_1_val_1.fq.gz'.format(wildcards.accession),
                                'results/trimmed_fastq/{}_2_val_2.fq.gz'.format(wildcards.accession)
                                ]
                return(input_files)
        else:
                input_file = ["results/trimmed_fastq/{}_trimmed.fq.gz".format(wildcards.accession)
                             ]
                return(input_file)

def get_index (wildcards):
		if wildcards.accession in config['mouse_runs']:
			return("results/salmon/mmu_GRCm38_index/")
		elif wildcards.accession in config['human_runs']:
			return('results/salmon/hsa_GRCh38_index/')

rule salmon_quant:
        output: "results/salmon/{accession}/quant.sf", "results/salmon/{accession}/lib_format_counts.json"
        input: 
		reads=get_input_files,
		index=get_index
        conda:
                "envs/salmon.yaml"
	threads: 4
        script:
                "quant_salmon.py"

rule salmon_get_lib_type:
	input: "results/salmon/{run_accession}/lib_format_counts.json"
	output: "results/salmon/{run_accession}/lib_type.txt"
        shell: "grep 'expected' {input} | awk '{{print $2}}' | sed 's/\"//g' | sed 's/,//g' > {output}"
