## A Snakefile for the testing the biological validity of FilTar's approach. Generates plots found in FilTar manuscript.

### Cumulative Plots

rule figure1:
	input:
		A549="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_exp.rds",
		HeLa="results/plots/hsa_PRJNA512378_miR-16-5p_HeLa_exp.rds",
		NMuMG="results/plots/mmu_PRJNA340017_miR-1199-5p_NMuMG_exp.rds",
		ESCs='results/plots/mmu_PRJNA270999_miR-294-3p_ESCs_exp.rds'
	output: 'results/plots/figure1.pdf'
	script: 'cumulative_plots.R'

#rule sup_fig8:
#	input:
#		A549='A549_multi_threshold_plot.rds',
#		HeLa='HeLa_multi_threshold_plot.rds',
#		NMuMG="NMuMG_multi_threshold_plot.rds",
#		ESCs="ESCs_multi_threshold_plot.rds"
#	output: 'results/plots/sup_fig8.png'
#	script: 'supplementary_figure_8.R'

rule get_cumulative_plot_expression_filtering_multi_plot:
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                canon_targets = "results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold= [0.1,0.5,1.0,5.0,10.0],
                x_lim=2.00
        threads: 16
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_exp_mp.png"
        script: "alt_utrs_deseq_exp_multiplot.R"

rule volcano_plots:
	input:
		quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
		quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
		canon_targets = "results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
		pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
	params:
		nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
		target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
		exp_threshold= [0.1,0.5,1.0,5.0,10.0],
		x_lim=2.00
	threads: 16
	output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_volcano.rds"
	script: "volcano_plots.R"

rule figure1_multi:
        input:
                A549="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_exp_mp.rds",
                HeLa="results/plots/hsa_PRJNA512378_miR-16-5p_HeLa_exp_mp.rds",
                NMuMG="results/plots/mmu_PRJNA340017_miR-1199-5p_NMuMG_exp_mp.rds",
                ESCs='results/plots/mmu_PRJNA270999_miR-294-3p_ESCs_exp_mp.rds'
        output: 'results/plots/figure1_mp.png'
        script: 'cumulative_plots.R'

rule sup_fig1:
        input:
                A549="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_sup_fig1.rds",
                HeLa="results/plots/hsa_PRJNA512378_miR-16-5p_HeLa_sup_fig1.rds",
                NMuMG="results/plots/mmu_PRJNA340017_miR-1199-5p_NMuMG_sup_fig1.rds",
                ESCs='results/plots/mmu_PRJNA270999_miR-294-3p_ESCs_sup_fig1.rds'
        output: 'results/plots/supplementary_figure1.png'
        script: 'cumulative_plots.R'

rule sup_fig1_multi:
        input:
                A549="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_sup_fig1_mp.rds",
                HeLa="results/plots/hsa_PRJNA512378_miR-16-5p_HeLa_sup_fig1_mp.rds",
                NMuMG="results/plots/mmu_PRJNA340017_miR-1199-5p_NMuMG_sup_fig1_mp.rds",
                ESCs='results/plots/mmu_PRJNA270999_miR-294-3p_ESCs_sup_fig1_mp.rds'
        output: 'results/plots/supplementary_figure1_mp.png'
        script: 'cumulative_plots.R'

rule figure2:
	input:
		A549="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_alt_utr.rds",
		HeLa="results/plots/hsa_PRJNA512378_miR-16-5p_HeLa_alt_utr.rds",
		NMuMG="results/plots/mmu_PRJNA340017_miR-1199-5p_NMuMG_alt_utr.rds",
		ESCs='results/plots/mmu_PRJNA270999_miR-294-3p_ESCs_alt_utr.rds'
	output: 'results/plots/figure2.png'
	script: 'cumulative_plots.R'

rule figure3:
	input:
		A549="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_alt_utr_old.rds",
		HeLa="results/plots/hsa_PRJNA512378_miR-16-5p_HeLa_alt_utr_old.rds",
		NMuMG="results/plots/mmu_PRJNA340017_miR-1199-5p_NMuMG_alt_utr_old.rds",
		ESCs='results/plots/mmu_PRJNA270999_miR-294-3p_ESCs_alt_utr_old.rds'
	output: 'results/plots/figure3.png'
	script: 'cumulative_plots.R'

rule supplementary_figure7:
	input:
		A343="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_alt_utr_old_no_filt.rds",
		HeLa="results/plots/hsa_PRJNA512378_miR-16-5p_HeLa_alt_utr_old_no_filt.rds",
		NMuMG="results/plots/mmu_PRJNA340017_miR-1199-5p_NMuMG_alt_utr_old_no_filt.rds",
		ESCs='results/plots/mmu_PRJNA270999_miR-294-3p_ESCs_alt_utr_old_no_filt.rds'
	output: 'results/plots/supplementary_figure7.png'
	script: 'cumulative_plots.R'

rule supplementary_figure2:
	input:
		U343="results/plots/hsa_PRJNA231155_miR-137-3p_U343_alt_utr_sup_fig.rds", 
		HeLa_9="results/plots/hsa_PRJNA512378_miR-145-5p_HeLa_alt_utr_sup_fig.rds",
		HeLa_11="results/plots/hsa_PRJNA512378_miR-155-5p_HeLa_alt_utr_sup_fig.rds",
		HeLa_1='results/plots/hsa_PRJNA512378_let-7c-5p_HeLa_alt_utr_sup_fig.rds'
	output: 'results/plots/supplementary_figure2.png'
	script: 'supplementary_figure2.R'

rule supplementary_figure3:
	output:
		sup_fig3a="results/plots/supplementary_figure3a.png",
		sup_fig3b="results/plots/supplementary_figure3b.png"
	script: "supplementary_figure3.R"


## Supplementary Data

rule supplementary_figure_1:
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                canon_targets = "results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0.1,
                x_lim=2.00
        threads: 16
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_sup_fig1.rds"
        script: "supplementary_figure1.R"

rule supplementary_figure_1_multi_plot:
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                canon_targets = "results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=[0.1,0.5,1.0,5.0,10.0],
                x_lim=1.20
        threads: 16
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_sup_fig1_mp.rds"
        script: "supplementary_figure1.R"

rule supplementary_data1_plots:
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                canon_targets = "results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0.1,
                x_lim=2.00
        threads: 16
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_not_used.rds"
        script: "supplementary_data1_plots.R"

rule supplementary_data1:
	input:
		HeLa3_1='results/plots/hsa_PRJNA271411_miR-503-5p_HeLa3_not_used.rds',
		HeLa3_2='results/plots/hsa_PRJNA271411_miR-494-3p_HeLa3_not_used.rds',
		HeLa3_3='results/plots/hsa_PRJNA271411_miR-103a-3p_HeLa3_not_used.rds',
		HeLa2='results/plots/hsa_PRJNA284262_miR-603_HeLa2_not_used.rds',
		HeLa1_1='results/plots/hsa_PRJNA229375_miR-124-3p_HeLa1_not_used.rds',
		HeLa1_2='results/plots/hsa_PRJNA229375_miR-155-5p_HeLa1_not_used.rds',
		HEK293_1='results/plots/hsa_PRJNA229375_miR-124-3p_HEK293_not_used.rds',
		HEK293_2='results/plots/hsa_PRJNA229375_miR-155-5p_HEK293_not_used.rds',
		Huh7_1='results/plots/hsa_PRJNA229375_miR-124-3p_Huh7_not_used.rds',
		Huh7_2='results/plots/hsa_PRJNA229375_miR-155-5p_Huh7_not_used.rds',
		IMR90='results/plots/hsa_PRJNA229375_miR-124-3p_Huh7_not_used.rds'
	output: 'results/plots/supplementary_data1.pdf'
	script: 'supplementary_data1.R'

rule supplementary_data3:
	input:
		U251='results/plots/hsa_PRJNA231155_miR-137-3p_U251_exp.rds',
		U343="results/plots/hsa_PRJNA231155_miR-137-3p_U343_exp.rds",
		Du145="results/plots/hsa_PRJNA292016_miR-141-3p_Du145_exp.rds",
		HBE14o="results/plots/hsa_PRJNA304643_miR-1343-3p_16HBE14o_exp.rds",
		U20S_1="results/plots/hsa_PRJNA223608_miR-155-5p_U20S_exp.rds",U20S_2="results/plots/hsa_PRJNA223608_miR-1-3p_U20S_exp.rds",
		NMuMG_1="results/plots/mmu_PRJNA340017_miR-200b-3p_NMuMG_exp.rds",NMuMG_2="results/plots/mmu_PRJNA340017_miR-429-3p_NMuMG_exp.rds",
		CD4_1='results/plots/mmu_PRJNA309441_miR-24-3p_CD4_exp.rds',CD4_2='results/plots/mmu_PRJNA309441_miR-27a-3p_CD4_exp.rds',
                CD4_3='results/plots/mmu_PRJNA309441_miR-23a-3p_CD4_exp.rds',
		HeLa_1="results/plots/hsa_PRJNA512378_let-7c-5p_HeLa_exp.rds",HeLa_2="results/plots/hsa_PRJNA512378_miR-107_HeLa_exp.rds",
                HeLa_3="results/plots/hsa_PRJNA512378_miR-10a-5p_HeLa_exp.rds",HeLa_4="results/plots/hsa_PRJNA512378_miR-124-3p_HeLa_exp.rds",
                HeLa_5="results/plots/hsa_PRJNA512378_miR-126-3p_HeLa_exp.rds",HeLa_6="results/plots/hsa_PRJNA512378_miR-126-5p_HeLa_exp.rds",
		HeLa_7="results/plots/hsa_PRJNA512378_miR-133b_HeLa_exp.rds",HeLa_8="results/plots/hsa_PRJNA512378_miR-142-3p_HeLa_exp.rds",
                HeLa_9="results/plots/hsa_PRJNA512378_miR-145-5p_HeLa_exp.rds",HeLa_10="results/plots/hsa_PRJNA512378_miR-146a-5p_HeLa_exp.rds",
                HeLa_11="results/plots/hsa_PRJNA512378_miR-155-5p_HeLa_exp.rds",HeLa_12="results/plots/hsa_PRJNA512378_miR-15a-5p_HeLa_exp.rds",
		HeLa_13="results/plots/hsa_PRJNA512378_miR-17-5p_HeLa_exp.rds",HeLa_14="results/plots/hsa_PRJNA512378_miR-193b-3p_HeLa_exp.rds",
                HeLa_15="results/plots/hsa_PRJNA512378_miR-200a-3p_HeLa_exp.rds",HeLa_16="results/plots/hsa_PRJNA512378_miR-200b-3p_HeLa_exp.rds",
                HeLa_17="results/plots/hsa_PRJNA512378_miR-200c-3p_HeLa_exp.rds",HeLa_18="results/plots/hsa_PRJNA512378_miR-206_HeLa_exp.rds",
		HeLa_19="results/plots/hsa_PRJNA512378_miR-210-3p_HeLa_exp.rds",HeLa_20="results/plots/hsa_PRJNA512378_miR-21-5p_HeLa_exp.rds",
                HeLa_21="results/plots/hsa_PRJNA512378_miR-31-5p_HeLa_exp.rds",HeLa_22="results/plots/hsa_PRJNA512378_miR-34a-5p_HeLa_exp.rds",
                HeLa_23="results/plots/hsa_PRJNA512378_miR-9-3p_HeLa_exp.rds",HeLa_24="results/plots/hsa_PRJNA512378_miR-9-5p_HeLa_exp.rds"
	output: 'results/plots/supplementary_data3.pdf'
	script: 'supplementary_data.R'

rule supplementary_data4:
        input:
                NMuMG_1="results/plots/mmu_PRJNA340017_miR-200b-3p_NMuMG_alt_utr.rds",NMuMG_2="results/plots/mmu_PRJNA340017_miR-429-3p_NMuMG_alt_utr.rds",
                HeLa_2="results/plots/hsa_PRJNA512378_miR-107_HeLa_alt_utr.rds",HeLa_3="results/plots/hsa_PRJNA512378_miR-10a-5p_HeLa_alt_utr.rds",
                HeLa_12="results/plots/hsa_PRJNA512378_miR-15a-5p_HeLa_alt_utr.rds"
        output: 'results/plots/supplementary_data4.pdf'
        script: 'supplementary_data4.R'

rule supplementary_data5:
	input:
		U251='results/plots/hsa_PRJNA231155_miR-137-3p_U251_alt_utr_old.rds',
		U343="results/plots/hsa_PRJNA231155_miR-137-3p_U343_alt_utr_old.rds",
		Du145="results/plots/hsa_PRJNA292016_miR-141-3p_Du145_alt_utr_old.rds",
		HBE14o="results/plots/hsa_PRJNA304643_miR-1343-3p_16HBE14o_alt_utr_old.rds",
		U20S_1="results/plots/hsa_PRJNA223608_miR-155-5p_U20S_alt_utr_old.rds",U20S_2="results/plots/hsa_PRJNA223608_miR-1-3p_U20S_alt_utr_old.rds",
		NMuMG_1="results/plots/mmu_PRJNA340017_miR-200b-3p_NMuMG_alt_utr_old.rds",NMuMG_2="results/plots/mmu_PRJNA340017_miR-429-3p_NMuMG_alt_utr_old.rds",
		CD4_1='results/plots/mmu_PRJNA309441_miR-24-3p_CD4_alt_utr_old.rds',CD4_2='results/plots/mmu_PRJNA309441_miR-27a-3p_CD4_alt_utr_old.rds',
                CD4_3='results/plots/mmu_PRJNA309441_miR-23a-3p_CD4_alt_utr_old.rds',
		HeLa_1="results/plots/hsa_PRJNA512378_let-7c-5p_HeLa_alt_utr_old.rds",HeLa_2="results/plots/hsa_PRJNA512378_miR-107_HeLa_alt_utr_old.rds",
                HeLa_3="results/plots/hsa_PRJNA512378_miR-10a-5p_HeLa_alt_utr_old.rds",HeLa_4="results/plots/hsa_PRJNA512378_miR-124-3p_HeLa_alt_utr_old.rds",
                HeLa_5="results/plots/hsa_PRJNA512378_miR-126-3p_HeLa_alt_utr_old.rds",HeLa_6="results/plots/hsa_PRJNA512378_miR-126-5p_HeLa_alt_utr_old.rds",
		HeLa_7="results/plots/hsa_PRJNA512378_miR-133b_HeLa_alt_utr_old.rds",HeLa_8="results/plots/hsa_PRJNA512378_miR-142-3p_HeLa_alt_utr_old.rds",
                HeLa_9="results/plots/hsa_PRJNA512378_miR-145-5p_HeLa_alt_utr_old.rds",HeLa_10="results/plots/hsa_PRJNA512378_miR-146a-5p_HeLa_alt_utr_old.rds",
                HeLa_11="results/plots/hsa_PRJNA512378_miR-155-5p_HeLa_alt_utr_old.rds",HeLa_12="results/plots/hsa_PRJNA512378_miR-15a-5p_HeLa_alt_utr_old.rds",
		HeLa_13="results/plots/hsa_PRJNA512378_miR-17-5p_HeLa_alt_utr_old.rds",HeLa_14="results/plots/hsa_PRJNA512378_miR-193b-3p_HeLa_alt_utr_old.rds",
                HeLa_15="results/plots/hsa_PRJNA512378_miR-200a-3p_HeLa_alt_utr_old.rds",HeLa_16="results/plots/hsa_PRJNA512378_miR-200b-3p_HeLa_alt_utr_old.rds",
                HeLa_17="results/plots/hsa_PRJNA512378_miR-200c-3p_HeLa_alt_utr_old.rds",HeLa_18="results/plots/hsa_PRJNA512378_miR-206_HeLa_alt_utr_old.rds",
		HeLa_19="results/plots/hsa_PRJNA512378_miR-210-3p_HeLa_alt_utr_old.rds",HeLa_20="results/plots/hsa_PRJNA512378_miR-21-5p_HeLa_alt_utr_old.rds",
                HeLa_21="results/plots/hsa_PRJNA512378_miR-31-5p_HeLa_alt_utr_old.rds",HeLa_22="results/plots/hsa_PRJNA512378_miR-34a-5p_HeLa_alt_utr_old.rds",
                HeLa_23="results/plots/hsa_PRJNA512378_miR-9-3p_HeLa_alt_utr_old.rds",HeLa_24="results/plots/hsa_PRJNA512378_miR-9-5p_HeLa_alt_utr_old.rds"
	output: 'results/plots/supplementary_data5.pdf'
	script: 'supplementary_data.R'

### Cumulative Plots

rule get_cumulative_plot_expression_filtering: # Figure 1 & Supplementary Data file 3
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                canon_targets = "results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0.1,
                x_lim=1.00
        threads: 16
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_exp.rds"
        script: "alt_utrs_deseq_exp.R"

rule get_cumulative_plot_alt_utrs_added_targets: # Figure 2 & Supplementary Data file 4
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                cl_targets= "results/targets/{species}_{cell_line}_msa_{miRNA}.sites.tsv",
                canon_targets ="results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0,
                x_lim=1.2
        threads: 2
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_alt_utr.rds"
        script: "alt_utrs_deseq.R"

rule noise_analysis: # Figure 2 & Supplementary Data file 4
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                canon_targets ="results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0,
                x_lim=1.2
        threads: 20
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_noise_analysis.tsv"
        script: "noise_analysis.R"




rule get_cumulative_plot_alt_utrs_removed_targets: # Figure 3 & Supplementary Data file 5
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                cl_targets= "results/targets/{species}_{cell_line}_msa_{miRNA}.sites.tsv",
                canon_targets ="results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0,
                x_lim=1.50
	threads: 2
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_alt_utr_old.rds"
        script: "alt_utrs_deseq_old_targets.R"

rule supplementary_figure_2_individual: # Supplementary Figure 2
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                cl_targets= "results/targets/{species}_{cell_line}_msa_{miRNA}.sites.tsv",
                canon_targets ="results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0,
                x_lim=2.2
	threads: 10
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_alt_utr_sup_fig.rds"
        script: "alt_utrs_deseq_sup_fig.R"

rule supplementary_figure_7_individual: # Supplementary Figure 7
        input:
                quant_mock= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line]['mock']),
                quant_real= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.cell_line][wildcards.miRNA]),
                cl_targets= "results/targets/{species}_{cell_line}_msa_{miRNA}.sites.tsv",
                canon_targets ="results/targets/{species}_msa_nr_{miRNA}.sites.tsv",
                pc_transcripts="results/bed/{species}_all_protein_coding_transcripts.txt"
        params:
                nontarget_site_types= ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                target_site_types = ['8mer-1a','7mer-m8','7mer-1a','6mer'],
                exp_threshold=0,
                x_lim=1.20
        threads: 5
        output: "results/plots/{species}_{project}_{miRNA}_{cell_line}_alt_utr_old_no_filt.rds"
        script: "alt_utrs_deseq_old_targets_no_filt.R"

### Other plots and data tables

rule get_target_stats: # Figure 4, supplementary figure 6,7 & 8, supplementary table 4 
	input:
		tissue='results/targets/{species}_{tissue}_msa_all.sites.tsv',
                control='results/targets/{species}_msa_nr_all.sites.tsv',
		quant= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.tissue]['mock']),
                pc_transcripts='results/bed/{species}_all_protein_coding_transcripts.txt'
	output: "results/targets/{species}_{project}_{tissue}_stats.txt"
	wildcard_constraints:
		tissue="((?!SRR).)*",
                project="((?!ske|bone).)*"
	script: 'get_stats.R'

rule supplementary_table_4: # supplementary_table_4
	input:
		U251='results/targets/hsa_PRJNA231155_U251_stats.txt',
		U343='results/targets/hsa_PRJNA231155_U343_stats.txt',
		Du145='results/targets/hsa_PRJNA292016_Du145_stats.txt',
		A549='results/targets/hsa_PRJNA304643_A549_stats.txt',
		HBE14o='results/targets/hsa_PRJNA304643_16HBE14o_stats.txt',
		HeLa='results/targets/hsa_PRJNA512378_HeLa_stats.txt',
		U20S='results/targets/hsa_PRJNA223608_U20S_stats.txt',
		Kidney='results/targets/hsa_PRJEB2445_kidney2_stats.txt',
		Lung='results/targets/hsa_PRJEB2445_lung_stats.txt',
		Skeletal_muscle='results/targets/hsa_PRJEB6971_skeletal_muscle_stats.txt',
		Thyroid='results/targets/hsa_PRJEB6971_thyroid_stats.txt',
		Bone_marrow='results/targets/hsa_PRJEB6971_bone_marrow_stats.txt',
		NMuMG='results/targets/mmu_PRJNA340017_NMuMG_stats.txt',
		ESCs='results/targets/mmu_PRJNA270999_ESCs_stats.txt',
		CD4='results/targets/mmu_PRJNA309441_CD4_stats.txt',
	output: 'results/plots/supplementary_table4.tsv'
	wildcard_constraints:
		project="((?!bone).)*"
	script: 'supplementary_table4.R'

rule figure_4_and_sup_fig_5:
	input:
		sup_table4='results/plots/supplementary_table4.tsv',
		hsa_all_targets='results/targets/hsa_msa_nr_all.sites.tsv',
		mmu_all_targets='results/targets/mmu_msa_nr_all.sites.tsv'
	output:	
		fig4='results/plots/figure4.png',
		sup_fig5='results/plots/supplementary_figure5.png'
	script: 'figure4.R'

rule sup_fig_7_and_8:
        input:
                sup_table4='results/plots/supplementary_table4.tsv',
		sup_table1='results/plots/supplementary_table1_raw.tsv',
                hsa_all_targets='results/targets/hsa_msa_nr_all.sites.tsv',
                mmu_all_targets='results/targets/mmu_msa_nr_all.sites.tsv'
	output:
		sup_fig5a='results/plots/supplementary_figure5a.png',
		sup_fig5b='results/plots/supplementary_figure5b.png'
	script: 'sup_fig5.R'


rule get_reannotation_stats: # Supplementary figure 2,3,4,5 and supplementary tables 1 and 3
	input:
		canonical="results/targets/{species}.utr.lengths.tsv",
		new='results/utrs/{species}_{tissue}.utr.lengths.tsv',
                pc_transcripts='results/bed/{species}_all_protein_coding_transcripts.txt',
                quant= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.tissue]['mock'])
	output: 'results/utrs/{project}_{species}_{tissue}_stats.tsv'
        wildcard_constraints:
                project="((?!hsa).)*"
	script: "get_reannotation_stats.R"

rule get_supplementary_table_1_raw:
	input:
                U251='results/utrs/PRJNA231155_hsa_U251_stats.tsv',
                U343='results/utrs/PRJNA231155_hsa_U343_stats.tsv',
                Du145='results/utrs/PRJNA292016_hsa_Du145_stats.tsv',
                A549='results/utrs/PRJNA304643_hsa_A549_stats.tsv',
                HBE14o='results/utrs/PRJNA304643_hsa_16HBE14o_stats.tsv',
                HeLa='results/utrs/PRJNA512378_hsa_HeLa_stats.tsv',
                U20S='results/utrs/PRJNA223608_hsa_U20S_stats.tsv',
                Kidney='results/utrs/PRJEB2445_hsa_kidney2_stats.tsv',
                Lung='results/utrs/PRJEB2445_hsa_lung_stats.tsv',
                Skeletal_muscle='results/utrs/PRJEB6971_hsa_skeletal_muscle_stats.tsv',
                Thyroid='results/utrs/PRJEB6971_hsa_thyroid_stats.tsv',
                Bone_marrow='results/utrs/PRJEB6971_hsa_bone_marrow_stats.tsv',
                NMuMG='results/utrs/PRJNA340017_mmu_NMuMG_stats.tsv',
                ESCs='results/utrs/PRJNA270999_mmu_ESCs_stats.tsv',
                CD4='results/utrs/PRJNA309441_mmu_CD4_stats.tsv'
	output: 'results/plots/supplementary_table1_raw.tsv'
	script: "supplementary_table1_raw.R"

rule get_supplementary_table_1:
	input: 'results/plots/supplementary_table1_raw.tsv'
	output: 'results/plots/supplementary_table1.tsv'
	script: "supplementary_table1.R"

rule get_expression_filtering_stats: # Supplementary tables 2 and 3
        input:
                canonical="results/targets/{species}.utr.lengths.tsv",
                pc_transcripts='results/bed/{species}_all_protein_coding_transcripts.txt',
                quant= lambda wildcards: expand("results/kallisto/{Run}/abundance.tsv", Run=config[wildcards.project][wildcards.tissue]['mock'])
        output: 'results/utrs/{project}_{species}_{tissue}_expression_stats.tsv'
        wildcard_constraints:
                project="((?!hsa).)*"
        script: "get_expression_stats.R"

rule get_supplementary_table_2_raw:
	input:
                U251='results/utrs/PRJNA231155_hsa_U251_expression_stats.tsv',
                U343='results/utrs/PRJNA231155_hsa_U343_expression_stats.tsv',
                Du145='results/utrs/PRJNA292016_hsa_Du145_expression_stats.tsv',
                A549='results/utrs/PRJNA304643_hsa_A549_expression_stats.tsv',
                HBE14o='results/utrs/PRJNA304643_hsa_16HBE14o_expression_stats.tsv',
                HeLa='results/utrs/PRJNA512378_hsa_HeLa_expression_stats.tsv',
                U20S='results/utrs/PRJNA223608_hsa_U20S_expression_stats.tsv',
                Kidney='results/utrs/PRJEB2445_hsa_kidney2_expression_stats.tsv',
                Lung='results/utrs/PRJEB2445_hsa_lung_expression_stats.tsv',
                Skeletal_muscle='results/utrs/PRJEB6971_hsa_skeletal_muscle_expression_stats.tsv',
                Thyroid='results/utrs/PRJEB6971_hsa_thyroid_expression_stats.tsv',
                Bone_marrow='results/utrs/PRJEB6971_hsa_bone_marrow_expression_stats.tsv',
                NMuMG='results/utrs/PRJNA340017_mmu_NMuMG_expression_stats.tsv',
                ESCs='results/utrs/PRJNA309441_mmu_CD4_expression_stats.tsv',
                CD4='results/utrs/PRJNA270999_mmu_ESCs_expression_stats.tsv'
	output: 'results/plots/supplementary_table2_raw.tsv'
	script: "supplementary_table2_raw.R"

rule get_supplementary_table_2:
	input: 'results/plots/supplementary_table2_raw.tsv'
	output: 'results/plots/supplementary_table2.tsv'
	script: "supplementary_table2.R"

rule get_supplementary_table_3:
	input:
		sup_table1_raw='results/plots/supplementary_table1_raw.tsv',
		sup_table2_raw='results/plots/supplementary_table2_raw.tsv'
	output: 'results/plots/supplementary_table3.tsv'
	script: 'supplementary_table3.R'

rule get_supplementary_figure_4:
	input:
		sup_table1_raw='results/plots/supplementary_table1_raw.tsv',
                PRJEB2445_single_end='reports/PRJEB2445_data/multiqc_hisat2.txt',
		PRJNA223608='reports/PRJNA223608_data/multiqc_hisat2.txt',
		PRJNA231155='reports/PRJNA231155_data/multiqc_hisat2.txt',
		PRJNA309441='reports/PRJNA309441_data/multiqc_hisat2.txt',
		PRJNA340017='reports/PRJNA340017_data/multiqc_hisat2.txt',
		PRJNA512378='reports/PRJNA512378_data/multiqc_hisat2.txt',
                PRJEB2445_paired_end='reports/paired_end/PRJEB2445_data/multiqc_hisat2.txt',
		PRJEB6971='reports/paired_end/PRJEB6971_data/multiqc_hisat2.txt',
		PRJNA270999='reports/paired_end/PRJNA270999_data/multiqc_hisat2.txt',
		PRJNA292016='reports/paired_end/PRJNA292016_data/multiqc_hisat2.txt',
		PRJNA304643='reports/paired_end/PRJNA304643_data/multiqc_hisat2.txt'
	output: 
		sup_fig4a='results/plots/supplementary_figure4a.png',
		sup_fig4b='results/plots/supplementary_figure4b.png'
	script: 'supplementary_figure4.R'

### Auxillary Rules ###

rule get_utr_lengths2: # get sequence lengths of reannotated 3'UTRs
	input:	'results/bed/{species}_{cell_line}.utr.full.bed'
	output: 'results/utrs/{species}_{cell_line}.utr.lengths.tsv'
	script: 'get_utr_lengths.R'

rule get_utr_lengths_canonical: # get sequence lengths of original 3'UTRs
        input:  'results/bed/canonical/{species}_3UTR.chr{chrom}.bed'
        output: 'results/targets/canonical/{species}_chr{chrom}.utr.lengths.tsv'
        script: 'get_utr_lengths.R'

rule aggregate_utr_lengths: # aggregate by chromosome
       input: lambda wildcards: expand("results/targets/canonical/{species}_chr{chrom}.utr.lengths.tsv", chrom=config['chromosomes'][wildcards.species], species=wildcards.species)
       output: "results/targets/canonical/{species}.utr.lengths.tsv"
       shell: "cat {input} | sed '1b;/tx/d' > {output}"

### thesis volcano plots ###

rule volcano1_thesis:
	input:
		U251='results/plots/hsa_PRJNA231155_miR-137-3p_U251_volcano.rds',
		U343="results/plots/hsa_PRJNA231155_miR-137-3p_U343_volcano.rds",
		Du145="results/plots/hsa_PRJNA292016_miR-141-3p_Du145_volcano.rds",
		HBE14o="results/plots/hsa_PRJNA304643_miR-1343-3p_16HBE14o_volcano.rds",
		U20S_1="results/plots/hsa_PRJNA223608_miR-155-5p_U20S_volcano.rds",
		U20S_2="results/plots/hsa_PRJNA223608_miR-1-3p_U20S_volcano.rds",
		NMuMG_1="results/plots/mmu_PRJNA340017_miR-200b-3p_NMuMG_volcano.rds",
		NMuMG_2="results/plots/mmu_PRJNA340017_miR-429-3p_NMuMG_volcano.rds",
		CD4_1='results/plots/mmu_PRJNA309441_miR-24-3p_CD4_volcano.rds',
		CD4_2='results/plots/mmu_PRJNA309441_miR-27a-3p_CD4_volcano.rds',
		CD4_3='results/plots/mmu_PRJNA309441_miR-23a-3p_CD4_volcano.rds'
	output: 'results/plots/volcano1_thesis.png'
	script: 'volcano_thesis.R'

rule volcano2_thesis:
	input:
		A549="results/plots/hsa_PRJNA304643_miR-1343-3p_A549_volcano.rds",HeLa_6="results/plots/hsa_PRJNA512378_miR-126-5p_HeLa_volcano.rds",
                HeLa_7="results/plots/hsa_PRJNA512378_miR-133b_HeLa_volcano.rds",HeLa_8="results/plots/hsa_PRJNA512378_miR-142-3p_HeLa_volcano.rds",
                HeLa_9="results/plots/hsa_PRJNA512378_miR-145-5p_HeLa_volcano.rds",HeLa_10="results/plots/hsa_PRJNA512378_miR-146a-5p_HeLa_volcano.rds",
                HeLa_11="results/plots/hsa_PRJNA512378_miR-155-5p_HeLa_volcano.rds",HeLa_12="results/plots/hsa_PRJNA512378_miR-15a-5p_HeLa_volcano.rds",
                HeLa_13="results/plots/hsa_PRJNA512378_miR-17-5p_HeLa_volcano.rds",HeLa_14="results/plots/hsa_PRJNA512378_miR-193b-3p_HeLa_volcano.rds",
                HeLa_15="results/plots/hsa_PRJNA512378_miR-200a-3p_HeLa_volcano.rds",HeLa_16="results/plots/hsa_PRJNA512378_miR-200b-3p_HeLa_volcano.rds",
	output: 'results/plots/volcano2_thesis.png'
	script: 'volcano_thesis2.R'


rule supplementary_data3_thesis3:
        input:
                HeLa_21="results/plots/hsa_PRJNA512378_miR-31-5p_HeLa_volcano.rds",HeLa_22="results/plots/hsa_PRJNA512378_miR-34a-5p_HeLa_volcano.rds",
                HeLa_23="results/plots/hsa_PRJNA512378_miR-9-3p_HeLa_volcano.rds",HeLa_24="results/plots/hsa_PRJNA512378_miR-9-5p_HeLa_volcano.rds",
                HeLa_1="results/plots/hsa_PRJNA512378_let-7c-5p_HeLa_volcano.rds",HeLa_2="results/plots/hsa_PRJNA512378_miR-107_HeLa_volcano.rds",
                HeLa_3="results/plots/hsa_PRJNA512378_miR-10a-5p_HeLa_volcano.rds",HeLa_4="results/plots/hsa_PRJNA512378_miR-124-3p_HeLa_volcano.rds",
                HeLa_17="results/plots/hsa_PRJNA512378_miR-200c-3p_HeLa_volcano.rds",HeLa_18="results/plots/hsa_PRJNA512378_miR-206_HeLa_volcano.rds",
                HeLa_19="results/plots/hsa_PRJNA512378_miR-210-3p_HeLa_volcano.rds",HeLa_20="results/plots/hsa_PRJNA512378_miR-21-5p_HeLa_volcano.rds"
        output: 'results/plots/volcano3_thesis.png'
        script: 'volcano_thesis3.R'

