## open device
pdf(file=snakemake@output[[1]])

readRDS(snakemake@input[['U251']])
readRDS(snakemake@input[['U343']])
readRDS(snakemake@input[['Du145']])
readRDS(snakemake@input[['HBE14o']])
readRDS(snakemake@input[['U20S_1']])
readRDS(snakemake@input[['U20S_2']])
readRDS(snakemake@input[['NMuMG_1']])
readRDS(snakemake@input[['NMuMG_2']])
readRDS(snakemake@input[['NMuMG_2']])
readRDS(snakemake@input[['CD4_1']])
readRDS(snakemake@input[['CD4_2']])
readRDS(snakemake@input[['CD4_3']])
readRDS(snakemake@input[['HeLa_1']])
readRDS(snakemake@input[['HeLa_2']])
readRDS(snakemake@input[['HeLa_3']])
readRDS(snakemake@input[['HeLa_4']])
readRDS(snakemake@input[['HeLa_5']])
readRDS(snakemake@input[['HeLa_6']])
readRDS(snakemake@input[['HeLa_7']])
readRDS(snakemake@input[['HeLa_8']])
readRDS(snakemake@input[['HeLa_9']])
readRDS(snakemake@input[['HeLa_10']])
readRDS(snakemake@input[['HeLa_11']])
readRDS(snakemake@input[['HeLa_12']])
readRDS(snakemake@input[['HeLa_13']])
readRDS(snakemake@input[['HeLa_14']])
readRDS(snakemake@input[['HeLa_15']])
readRDS(snakemake@input[['HeLa_16']])
readRDS(snakemake@input[['HeLa_17']])
readRDS(snakemake@input[['HeLa_18']])
readRDS(snakemake@input[['HeLa_19']])
readRDS(snakemake@input[['HeLa_20']])
readRDS(snakemake@input[['HeLa_21']])
readRDS(snakemake@input[['HeLa_22']])
readRDS(snakemake@input[['HeLa_23']])
readRDS(snakemake@input[['HeLa_24']])

dev.off()

