rule index_maf_files:
        input:
           maf="data/maf_{species}/chr{chrom}.maf",
        output:
           protected("data/{species}_chr{chrom}.mafindex")
        conda: 'envs/biopython.yaml'
        benchmark:
           "benchmarks/{species}_chr{chrom}.mafindex.log"
        script:
           "biopython_maf_processing.py"

rule biopython_get_msa: 
        input: 
           maf="data/maf_{species}/chr{chrom}.maf", 
           bed="results/bed/{species}_{tissue}_{feature}.chr{chrom}.bed", 
           maf_index="data/{species}_chr{chrom}.mafindex", 
           shell_script="exe/targetscan7/convert_fasta_to_tsv.sh" 
        output: 
           "results/msa/{species}_{tissue}_chr{chrom}_{feature}_msa.tsv" 
        conda: 
           "envs/biopython.yaml" 
        script: 
           "biopython_maf_processing2.py"
