#!/bin/bash

#    FilTar: Integrating RNA-Seq data to improve microRNA target prediction accuracy in animals
#    Copyright (C) 2019 Thomas Bradley
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>

rule mirna_species_fasta:
        input:
           "data/mature.fa"
        output:
           "data/mirbase_mature_{species}.fa"
        shell:
           "grep -A 1 {wildcards.species} {input} | awk '{{ print $1 }}' | sed 's/--//g' | sed '/^$/d' > {output}"

rule filter_mirna_species_fasta:
	input: "data/mirbase_mature_{species}.fa"
	output: "data/mirbase_mature_{species}.filtered.fa"
	conda: "envs/biopython.yaml"
	script: "filter_mirna_fasta.py"
