rule index_bam:
        input: "results/bam/run/hsa/{accession}.bam.sorted"
        output: "results/bam/run/hsa/{accession}.bam.sorted.bai"
        conda: "../with_reannotation/map_reads/hisat2/envs/hisat2.yaml"
        shell: "samtools index {input}"

rule samtools_view:
        input:
                bam="results/bam/run/hsa/{accession}.bam.sorted",
                bam_index="results/bam/run/hsa/{accession}.bam.sorted.bai"
        output: "{accession}.bam"
        wildcard_constraints:
                accession="^SRR.*"
        params:
                chromosome='1',  
                start='23,000,000',   # 103,398,635-103,415,104 
                end='24,000,000'
        conda: "../with_reannotation/map_reads/hisat2/envs/hisat2.yaml"
        shell: "samtools view -b {input.bam} '{params.chromosome}:{params.start}-{params.end}'  > {output}"

rule index_bam2:
        input: "{accession}.bam"
        output: "{accession}.bam.bai"
        wildcard_constraints:
                accession="^SRR.*"
        conda: "../with_reannotation/map_reads/hisat2/envs/hisat2.yaml"
        shell: "samtools index {input}"
