mirnas: [aae-miR-277-3p]                 # if blank, all miRNA for a given species are used 
transcripts: []                          # if blank, all available transcripts for a given species are used

species: aae                             # use first letter of genus name, and first two letters of species name
context: reference                          # for standard target prediction with no RNA-Seq data, set context to 'reference'
TPM_expression_threshold: 0.0
prediction_algorithm: TargetScan7        # select from 'TargetScan7' or 'miRanda'
reannotation: False                       # Whether to reannotate 3'UTRs or not
conservation: False                      # Where possible, whether to determine conservation of target sites or not using MSAs
sequence_data_source: ENA                # select from 'ENA','SRA' or 'User'

genome_index_type: standard              # 'standard' option requires ~8GB of memory. Otherwise, the 'splice-aware' option reuires ~200GB of memory
use_high_conf_mirs_only: True
