#!/bin/bash

subworkflow main_workflow:
        workdir: ".."
        snakefile: "../Snakefile"

rule prep_mirna_seeds:
        input:                      
           data="data/mature.fa",
           script="exe/get_mirna_seeds.sh"
        output:
           "results/mature_mirna_seed.tsv"
        shell:
           "{input.script} {input.data} > {output}"

rule prep_mirna_family_file:
        input:
           mature_mirna_seeds="results/mature_mirna_seed.tsv"
        output:
           "results/mirna_family.tsv",
        script:
           "get_mirna_family.R" # this is an awful hack and really needs to be fixed

rule download_targetscan_data1:
        input:
        output:
            "exe/targetscan7/targetscan_70.pl"
        shell:
            "cd exe/targetscan7 && wget http://www.targetscan.org/vert_72/vert_72_data_download/targetscan_70.zip && unzip targetscan_70.zip && rm UTR_Sequences_sample.txt miR_Family_info_sample.txt\
 targetscan_70_output.txt README_70.txt targetscan_70.zip"

rule targetscan_sites:
	input:
           msa="results/utrs/longest/{species}_chr{chrom}_msa.tsv",
           mirna_families=ancient("results/mirna_family.tsv"),
           script="exe/targetscan7/targetscan_70.pl"
	output:
           "results/targets/longest_utrs/{species}_chr{chrom}_msa.sites.tsv"
	benchmark:
           "benchmarks/{species}_chr{chrom}_msa.sites.log"
	shell:
           "{input.script} {input.mirna_families} {input.msa} {output}"

rule cat_sites:
	input: expand("results/targets/longest_utrs/hsa_chr{chrom}_msa.sites.tsv", chrom=config['chromosomes']['human'])
	output: "results/hsa_msa_sites.tsv"
	shell: "cat {input} | sed '1b;/Gene/d'  > {output}" # cat and delete all headers except for the first one

