#!/bin/bash

rule trim_single_end_reads:
       input: 
           "data/single_end/{accession}.fastq.gz"
       output: 
           "results/trimmed_fastq/{accession}_trimmed.fq.gz",
           "results/trimmed_fastq/{accession}.fastq.gz_trimming_report.txt"
       wildcard_constraints: 
           accession="((?!_[1-2]).)*"
       conda: 
          "envs/trim-galore.yaml"
       benchmark:
          "benchmarks/trim_galore/{accession}.log"
       shell:
          "trim_galore --output_dir results/trimmed_fastq/  --length 35 --stringency 4 {input}"

rule trim_paired_end_reads:
       input:
          file1="data/paired_end/{accession}_1.fastq.gz",
          file2="data/paired_end/{accession}_2.fastq.gz"
       output:
           "results/trimmed_fastq/{accession}_1_val_1.fq.gz",
           "results/trimmed_fastq/{accession}_2_val_2.fq.gz",
           "results/trimmed_fastq/{accession}_1.fastq.gz_trimming_report.txt",
           "results/trimmed_fastq/{accession}_2.fastq.gz_trimming_report.txt"
       conda:
          "envs/trim-galore.yaml"
       benchmark:
          "benchmarks/trim_galore/{accession}.log"
       shell:
          "trim_galore --output_dir results/trimmed_fastq/ --length 35 --stringency 4 --paired {input.file1} {input.file2}"
