#!/bin/bash

#    FilTar: Integrating RNA-Seq data to improve microRNA target prediction accuracy in animals
#    Copyright (C) 2019 Thomas Bradley
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>


rule download_single_end_fastq:
    output:
        "data/single_end/{accession}.fastq",
    conda:
        "workflow/envs/sra-tools.yaml"
    threads: 20
    shell:
        "fasterq-dump -O data/single_end/ --threads {threads} {wildcards.accession}"


rule download_paired_end_fastq:
    output:
        "data/paired_end/{accession}_1.fastq",
        "data/paired_end/{accession}_2.fastq",
    conda:
        "workflow/envs/sra-tools.yaml"
    threads: 20
    shell:
        "fasterq-dump -O data/paired_end/ --threads {threads} {wildcards.accession}"


rule compress_single_end_fastq_files:
    input:
        "data/single_end/{accession}.fastq",
    output:
        "data/single_end/{accession}.fastq.gz",
    shell:
        "gzip {input}"


rule compress_paired_end_fastq_files:
    input:
        file1="data/paired_end/{accession}_1.fastq",
        file2="data/paired_end/{accession}_2.fastq",
    output:
        "data/paired_end/{accession}_1.fastq.gz",
        "data/paired_end/{accession}_2.fastq.gz",
    shell:
        "gzip {input.file1} {input.file2}"
