configfile: "../config/accession_mappings.yaml"
configfile: "../config/lib_types.yaml"
configfile: "../config/matedness.yaml"
configfile: "../config/projects.yaml"
configfile: "../config/species_basic.yaml"
configfile: "../config/species_sequencing.yaml"
configfile: "config/validation.yaml"

include: "../sub_snakemake/data_download/ENA/Snakefile"
#include: "../sub_snakemake/qc/Snakefile"
include: "../sub_snakemake/trim_reads/trim_galore/Snakefile"
include: "../sub_snakemake/map_reads/hisat2/Snakefile"
include: "../sub_snakemake/APAtrap/Snakefile"
include: "../sub_snakemake/reannotate_3utrs/Snakefile"
include: "../sub_snakemake/quant_reads/salmon/Snakefile"
include: "../sub_snakemake/quant_reads/kallisto/Snakefile"
include: "../sub_snakemake/get_utr_and_cds/Snakefile" # A duplicated snakemake otherwise we would need to copy very large maf files in the root and validation directories
include: "../sub_snakemake/target_prediction/targetscan/Snakefile"
include: "../sub_snakemake/canonical_targets/Snakefile"
include: "sub_snakemake/cumulative_plots/Snakefile"

rule all:
     input: #expand("results/single_end_salmon/{accession}/", accession=config['PRJNA229375']['HeLa']['mock']),
            #expand("results/single_end_salmon/{accession}/", accession=config['PRJNA229375']['HeLa']['miR-124']),
            #expand("results/hsa_chr{chrom}_msa.contextpp.tsv", chrom=config['chromosomes']['human']),
            #expand("results/{miRNA}_{cell_line}_cumulative_plot.png", cell_line=config['PRJNA229375']['cell_lines'], miRNA=config['PRJNA229375']['miRNAs']),
            #expand("results/{sample}.bedgraph", sample=config["all_validation_samples"]),
            #expand("results/hsa_3UTR_chr{chrom}.bed", chrom=config["chromosomes"]["human"]),
            #expand("results/hsa_chr{chrom}_msa.tsv", chrom=config["chromosomes"]["human"] )
            #expand("results/hsa_chr{chrom}_msa.sites.tsv", chrom=config["chromosomes"]["human"])
            #expand("results/miR-124_{cell_line}_cumulative_plot.png", cell_line=config['PRJNA229375']['cell_lines'] ),
            #expand("results/miR-155_{cell_line}_cumulative_plot.png", cell_line=config['PRJNA229375']['cell_lines2'] )
            #expand("results/{cell_line}.utr.lengths.tsv", cell_line=config['PRJNA229375']['cell_lines3'])
            #expand("results/{cell_line}.sites.tsv", cell_line=config['PRJNA229375']['cell_lines3']),
            #expand("results/miR-124-3p_{cell_line}_alt_utr.png", cell_line=config['PRJNA229375']['cell_lines']),
            #expand("results/PRJNA229375_miR-155-5p_{cell_line}_alt_utr_tmp.png", cell_line=config['PRJNA229375']['cell_lines2']),
            #expand("results/PRJNA229375_miR-124-3p_{cell_line}_alt_utr_tmp.png", cell_line=config['PRJNA229375']['cell_lines']),
            #expand("results/PRJNA229375_miR-155-5p_{cell_line}_exp.png", cell_line=config['PRJNA229375']['cell_lines2']),
            #expand("results/PRJNA229375_miR-124-3p_{cell_line}_exp.png", cell_line=config['PRJNA229375']['cell_lines']),
            #expand("results/PRJNA231560_{miRNAs}_HeLa_alt_utr_tmp.png", miRNAs=config['PRJNA231560']['miRNAs']),
            #expand("results/PRJNA271411_{miRNAs}_HeLa_alt_utr_tmp.png", miRNAs=config['PRJNA271411']['miRNAs']),
            #expand("results/PRJNA223608_{miRNAs}_U20S_alt_utr_tmp.png", miRNAs=config['PRJNA223608']['miRNAs']),
            #"results/GRCh38.idx",
            #expand("results/single_end_kallisto/{accession}/abundance.tsv", accession=config['PRJNA223608']['all_runs']),
            #expand("results/single_end_kallisto/{accession}/abundance.tsv", accession=config['PRJNA231560']['all_runs']),
            #expand("results/kallisto/{accession}/abundance.tsv", accession=config['PRJNA187476']['all_runs']),
            #expand("results/kallisto/{accession}/abundance.tsv", accession=config['PRJNA292016']['all_runs']),
            #expand("results/kallisto/{accession}/abundance.tsv", accession=config['PRJNA165157']['all_runs']),
            #expand("results/kallisto/{accession}/abundance.tsv", accession=config['PRJNA271411']['all_runs']),
            #expand("results/kallisto/{accession}/abundance.tsv", accession=config['PRJNA304643']['all_runs']),
            #expand("results/kallisto/{accession}/abundance.tsv", accession=config['PRJNA270999']['all_runs'])
            # "results/targets/specific/hsa_U343.sites.tsv", "results/targets/specific/hsa_16HBE14o.sites.tsv",
            # "results/targets/specific/hsa_A549.sites.tsv", "results/targets/specific/hsa_Du145.sites.tsv",
             "results/plots/hsa_PRJNA231155_miR-137-3p_U343_exp.png", "results/plots/hsa_PRJNA231155_miR-137-3p_U343_alt_utr.png",
             "results/plots/hsa_PRJNA292016_miR-141-3p_Du145_exp.png", "results/plots/hsa_PRJNA292016_miR-141-3p_Du145_alt_utr.png",
             "results/plots/hsa_PRJNA304643_miR-1343-3p_A549_exp.png", "results/plots/hsa_PRJNA304643_miR-1343-3p_A549_alt_utr.png",
             "results/plots/hsa_PRJNA304643_miR-1343-3p_16HBE14o_exp.png", "results/plots/hsa_PRJNA304643_miR-1343-3p_16HBE14o_alt_utr.png",
             "results/plots/hsa_PRJNA229375_miR-124-3p_HeLa_exp.png", "results/plots/hsa_PRJNA229375_miR-124-3p_HeLa_alt_utr.png",
             "results/plots/hsa_PRJNA229375_miR-155-5p_HeLa_exp.png", "results/plots/hsa_PRJNA229375_miR-155-5p_HeLa_alt_utr.png",
             "results/plots/hsa_PRJNA229375_miR-124-3p_HEK293_exp.png", "results/plots/hsa_PRJNA229375_miR-124-3p_HEK293_alt_utr.png",
             "results/plots/hsa_PRJNA229375_miR-155-5p_HEK293_exp.png", "results/plots/hsa_PRJNA229375_miR-155-5p_HEK293_alt_utr.png",
             "results/plots/hsa_PRJNA229375_miR-124-3p_Huh7_exp.png", "results/plots/hsa_PRJNA229375_miR-124-3p_Huh7_alt_utr.png",
             "results/plots/hsa_PRJNA229375_miR-155-5p_Huh7_exp.png", "results/plots/hsa_PRJNA229375_miR-155-5p_Huh7_alt_utr.png",
             "results/plots/hsa_PRJNA229375_miR-124-3p_IMR90_exp.png", "results/plots/hsa_PRJNA229375_miR-124-3p_IMR90_alt_utr.png",
              expand("results/targets/{species}_{tissue}_chr{chrom}_msa.contextpp.tsv", species='hsa', tissue='HeLa', chrom=config['chromosomes']['hsa']),
              #expand("results/targets/canonical/{species}_chr{chrom}_msa.contextpp.tsv", species='hsa', chrom=config['chromosomes']['hsa'])
