#!/bin/bash

def get_species(wildcards):
	return(wildcards.genus_species.lower())

#rule download_mirna_data:
#       input:
#       output:
#          "data/mature.fa"
#       shell:
#          "wget --directory-prefix=data/ ftp://mirbase.org/pub/mirbase/CURRENT/mature.fa.gz && gunzip {output}"

rule get_gtf_file:
     output: "data/{genus_species}.{build}.94.gtf"
     params: get_species
     shell: "rsync -av rsync://ftp.ensembl.org/ensembl/pub/release-94/gtf/{params}/{wildcards.genus_species}.{wildcards.build}.94.gtf.gz data/ && gunzip data/{wildcards.genus_species}.{wildcards.build}.94.gtf.gz && sed 's/^chr//g' data/{wildcards.genus_species}.{wildcards.build}.94.gtf > tmp && mv tmp data/{wildcards.genus_species}.{wildcards.build}.94.gtf"

rule download_fasta:
        input:
        output: "data/{genus_species}.{build}.dna.chromosome.{chrom}.fa.gz"
        params: get_species
        shell: "rsync -av rsync://ftp.ensembl.org/ensembl/pub/release-94/fasta/{params}/dna/{wildcards.genus_species}.{wildcards.build}.dna.chromosome.{wildcards.chrom}.fa.gz data/"

rule decompress_dna_file:
        input: "data/{species_prefix}.dna.chromosome.{chrom}.fa.gz"
        output: "data/{species_prefix}.dna.chromosome.{chrom}.fa"
        conda: "envs/pigz.yaml"
        threads: 8
        shell: "pigz -p {threads} -d {input}"

rule download_maf_files_human:
        input:
        output:
           protected("data/maf_hsa/chr{chrom}.maf")
        shell:
           "wget --directory-prefix=data/maf_hsa/ -nv http://hgdownload.soe.ucsc.edu/goldenPath/hg38/multiz100way/maf/chr{wildcards.chrom}.maf.gz && gunzip {output}.gz"

rule download_maf_files_mouse:
        input:
        output:
           protected("data/maf_mmu/chr{chrom}.maf")
        shell:
           "wget --directory-prefix=data/maf_mmu/ -nv http://hgdownload.cse.ucsc.edu/goldenPath/mm10/multiz60way/maf/chr{wildcards.chrom}.maf.gz && gunzip {output}.gz"

rule download_cdna_file:
        output: "data/{genus_species}.{build}.cdna.all.fa.gz"
        params: get_species
        shell: "rsync -av rsync://ftp.ensembl.org/ensembl/pub/release-94/fasta/{params}/cdna/{wildcards.genus_species}.{wildcards.build}.cdna.all.fa.gz data"

rule decompress_cdna_file:
        input: "data/{species_prefix}.cdna.all.fa.gz"
        output: "data/{species_prefix}.cdna.all.fa"
        shell: "gunzip {input}"
