#!/bin/bash

def get_species(wildcards):
        if wildcards.species_prefix == 'Homo_sapiens.GRCh38':
                return('homo_sapiens')
        if wildcards.species_prefix == 'Mus_musculus.GRCm38':
                return('mus_musculus')

rule get_gtf_file:
     output: "data/{species_prefix}.94.gtf"
     params: get_species
     shell: "wget --directory-prefix=data/ ftp://ftp.ensembl.org/pub/release-94/gtf/{params}/{wildcards.species_prefix}.94.gtf.gz && gunzip data/{wildcards.species_prefix}.94.gtf.gz && sed -i 's/^/chr/g' data/{wildcards.species_prefix}.94.gtf"

rule download_maf_files_human:
        input:
        output:
           protected("data/maf_hsa/chr{chrom}.maf")
        shell:
           "wget --directory-prefix=data/maf_hsa/ -nv http://hgdownload.soe.ucsc.edu/goldenPath/hg38/multiz100way/maf/chr{wildcards.chrom}.maf.gz && gunzip {output}.gz"

rule download_maf_files_mouse:
        input:
        output:
           protected("data/maf_mmu/chr{chrom}.maf")
        shell:
           "wget --directory-prefix=data/maf_mmu/ -nv http://hgdownload.cse.ucsc.edu/goldenPath/mm10/multiz60way/maf/chr{wildcards.chrom}.maf.gz && gunzip {output}.gz"
