name: CI

on:
  push:
    branches: [ master, use_github_actions ]
  pull_request:
    branches: [ master, use_github_actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          miniforge-variant: Miniforge3
          miniforge-version: latest
          conda-version: 25.3.0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gzip
          sudo ln -s /bin/tar /bin/gtar || true

      - name: Create conda environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info -a
          conda config --add channels defaults
          conda config --add channels conda-forge
          conda config --add channels bioconda
          conda create -q -n test-environment snakemake=8.30.0 python=3.12

      - name: Activate environment and install dependencies
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          conda activate test-environment
          Rscript -e 'install.packages("remotes", repos="https://cloud.r-project.org")'
          Rscript -e 'remotes::install_github("TBradley27/filtar_R")'
          Rscript -e 'install.packages("testthat", repos="https://cloud.r-project.org")'
          snakemake --version

      - name: Run Snakemake and R tests
        run: |
          conda activate test-environment
          snakemake --cores 1 --use-conda -p results/targets/mmu/oocyte_chrY.contextpp.tsv --config sequence_data_source=SRA conservation=False reannotation=False mirnas="['mmu-miR-188-5p']" transcripts="['ENSMUST00000189888.7']" TPM_expression_threshold=0 prediction_algorithm=TargetScan7
          head results/targets/mmu/oocyte_chrY.contextpp.tsv || true
          rm -f results/targets/mmu/oocyte_chrY.contextpp.tsv || true
          snakemake --cores 1 --use-conda -p results/targets/miRanda/mmu/oocyte/chrY.tsv --config sequence_data_source=SRA conservation=False reannotation=False mirnas="['mmu-miR-188-5p']" transcripts="['ENSMUST00000189888.7']" TPM_expression_threshold=0 prediction_algorithm=miRanda
          head results/targets/miRanda/mmu/oocyte/chrY.tsv || true
          snakemake --cores 1 --use-conda -p results/targets/mmu/oocyte_chrY.contextpp.tsv --config sequence_data_source=SRA conservation=True reannotation=False mirnas="['mmu-miR-188-5p']" transcripts="['ENSMUST00000189888.7']" TPM_expression_threshold=0 prediction_algorithm=TargetScan7
          head results/targets/mmu/oocyte_chrY.contextpp.tsv || true
          R -e 'isTRUE(testthat::test_file("scripts/targetscan_test.R")[[1]]$passed)'
